[tool.black]
include = '\.pyi?$'
line-length = 120
skip-string-normalization = true

[tool.pycln]
all = true

[tool.isort]
src_paths=['src', 'tests']
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
filename = "*.py"
max-line-length = 120
additional_dependencies = ['flake8-bugbear']
ignore = ['E24','E121','E122','E123','E124','E126','E226','E265','E305','E402','F401','F405','E501','E704','F403','F841','W503','W605']
statistics = true
count = true

[tool.mypy]
files = ['src/', 'tests/', 'setup.py']
strict = true
show_error_codes = true
enable_error_code = ['ignore-without-code', 'redundant-expr', 'truthy-bool']
warn_unreachable = true
ignore_missing_imports = true
